<?php

namespace Drupal\example\Form;

use Drupal\Core\Entity\ContentEntityForm;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Class EventForm
 * @package Drupal\example\Form
 *
 *
 */
class EventForm extends ContentEntityForm {

  /**
   * {@inheritdoc}
   *
   * We use save(), as submitForm() does not save the entity, so we might end up
   * with an empty id.
   */
  public function save(array $form, FormStateInterface $form_state) {
    $ret = parent::save($form, $form_state); // TODO: Change the autogenerated stub

    drupal_set_message($this->t('Successfully saved the event %title', array(
      '%title' => $this->getEntity()->label(),
    )));

    $form_state->setRedirect('entity.event.canonical', array(
      'event' => $this->getEntity()->id(),
    ));

    return $ret;
  }


}